### ISSUE TITLE
Standardisation with warping

### ISSUE THREAD

**Issue by Elleaume** [amarquand/PCNtoolkit#115]
Hello, 

First, thank you for the great work on this toolbox!
I'm using Bayesian Linear Regression with SinhArcsinh warping for my project with as response variables the Freesurfer's outputs of brain MRIs.

I possibly wanted to standardise my covariates and response variable and tried to use the outscaler and inscaler arguments directly accessible in the toolbox and was confronted to some errors before noticing that there was a mention "TODO: Warping for scaled data" and "outscaler not yet supported warping" in the code of the toolbox in the estimate function.

So I wonder:
1) do you recommend standardizing the data or is it useless in this case?
2) If I can get around the problem by standardizing my data before calling the toolbox functions?

Thank you very much for your help!

**Comment by amarquand** [comment]
Dear Camille, 

Indeed we have not implemented the inscalar option for warping right now. This is because the warp itself can change the scale of the data which makes it somewhat complicated when a standardization or scaling transform is also applied together with the warp. I would recommend to use unstandardized data for the responses (i.e. leave the default value for outscalar) and the warp should be flexible enough to handle differences in the scaling of different response variables. there is no harm in scaling the covariates. 

If you really want to standardize your response variables, you can do it external to the toolbox as you have indicated although then you would need to be careful to make sure you preserve a proper training test split and error metrics that are sensitive to the scale of the response variables (e.g. MSE) would need to be interpreted with respect to the standardized data. Note however that I would really not expect this to improve performance. 

I hope that helps,
Andre.

**Comment by Elleaume** [comment]
Thank you Andre for your answer and clarifications.

Best, 
Camille
