### ISSUE TITLE
Problem in apply_normative_models.ipynb with colab

### ISSUE THREAD

**Issue by hanbing-gao** [amarquand/PCNtoolkit#120]
Hi,

I tried to run the apply_normative_models.ipynb with colab, when I run this part:

`from pcntoolkit.normative import estimate, predict, evaluate`

I got:

> RuntimeError: 
> Could not import 'mkl'.  If you are using conda, update the numpy
> packages to the latest build otherwise, set MKL_THREADING_LAYER=GNU in
> your environment for MKL 2018.
> 
> If you have MKL 2017 install and are not in a conda environment you
> can set the Theano flag blas.check_openmp to False.  Be warned that if
> you set this flag and don't set the appropriate environment or make
> sure you have the right version you *will* get wrong results.

which was still working days before. Not sure if this happens because there might have been some updates in Colab.
I tried to install mkl again for different versions but did not work.

**Comment by amarquand** [comment]
Hi - This is definitely a problem related to your environment. Have you updated some packages? Please try reinstalling in a clean environment. Note that there is an incompatibility between Theano and the most recent versions of numpy (see the setup.py in the main branch for details about that). I would also make sure you install numpy, mkl etc using conda (not pip).

**Comment by adamnarai** [comment]
Hi,
I have exactly the same issue, the script was working fine in colab just a few weeks ago and now I get the same error.

**Comment by amarquand** [comment]
If you are working in colab, I suspect that google have google have updated the versions of the libraries you get by default without you knowing it. You could try installing the required packages for pcntoolkit (especially pymc3/Theano) manually. One thing that you might like to try is downgrading numpy because there are known problems with the most recent versions, but we need to change the version of pymc3 to fix it (work in progress). Check the setup.py file for the supported versions.
