### ISSUE TITLE
Bug in metric evaluation for warped BLR

### ISSUE THREAD

**Issue by marlvan** [amarquand/PCNtoolkit#89]
I believe there is an error in line 488 of normative.py. Currently reads:

mf = evaluate(Ytest[:, np.newaxis], Yhati, S2=S2i, 
                                      mY=np.std(yw), sY=np.mean(yw), 
                                      nlZ=nm.neg_log_lik, nm=nm, Xz_tr=Xz_tr, 
                                      alg=alg, metrics = metrics)

but in the evaluate function specifies mY as the mean, and sY as the standard deviation, and they're written opposite.

**Comment by amarquand** [comment]
Hi - Thanks for pointing this out (and sorry for the slow response). You are correct, this is a bug and we have now corrected it. For information, the mean and std are only used in the estimation of the mean standardized log loss so the impact of this bug is minor. This fix will be included in v0.25
